# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: "Lehre"
    pre: "<i class='fas fa-chalkboard-teacher'></i>&ensp;"
    url: "/lehre/main"
    weight: 100
  - name: "Statistik I"
    pre: "<i class='fas fa-chart-pie'></i>&ensp;"
    url: "/lehre/main#statistik-i"
    parent: 'Lehre'
    weight: 101
  - name: "Statistik II"
    pre: "<i class='fas fa-chart-bar'></i>&ensp;"
    url: "/lehre/main#statistik-ii"
    parent: "Lehre"
    weight: 102
  - name: "Multivariat"
    pre: "<i class='fas fa-bezier-curve'></i>&ensp;"
    url: "/lehre/main#multivariat"
    parent: "Lehre"
    weight: 103
  - name: "KliPPs Methoden"
    pre: "<i class='fas fa-chart-line'></i>&ensp;"
    url: "/lehre/main#klipps"
    parent: "Lehre"
    weight: 104
  - name: "Forschungsmod. F&E"
    pre: "<i class='fas fa-laptop-code'></i>&ensp;"
    url: "/lehre/main#MSc5_fe"
    parent: "Lehre"
    weight: 105

  - name: "LIFOS"
    pre: "<i class='fas fa-book-open'></i>&ensp;"
    url: '/lifos/main'
    weight: 200
  - name: "LIFOS Grundlagen"
    pre: "<i class='far fa-folder-open'></i>&ensp;"
    url: '/lifos/main#lifos-grundlagen'
    parent: "LIFOS"
    weight: 201
  - name: "LIFOS Extras"
    pre: "<i class='fab fa-gitlab'></i>&ensp;"
    url: '/lifos/main#lifos-extras'
    parent: "LIFOS"
    weight: 202

  - name: "Projekte"
    pre: "<i class='fas fa-laptop'></i>&ensp;"
    url: '/projekte/main'
    weight: 300

  - name: "Extras"
    pre: "<i class='fas fa-wand-sparkles'></i>&ensp;"
    url: '/under-construction'
    weight: 400

  - name: "tigeR"
    pre: "<i class='fas fa-paw'></i>&ensp;"
    url: 'https://tiger.uni-frankfurt.de/app/shinytigeR'
    weight: 500  
  # - name: "Bayes"
  #   pre: "<i class='fa-solid fa-dice-d20'></i>&ensp;"
  #   url: '/extras/main#bayes'
  #   parent: 'Extras'
  #   weight: 401
  # 
  # - name: "stuart"
  #   pre: "<i class='fa fa-bugs'></i>&ensp;"
  #   url: '/extras/main#stuart'
  #   parent: 'Extras'
  #   weight: 402


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
