# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: "Lehre"
    pre: "<i class='fas fa-chalkboard-teacher'></i>&ensp;"
    url: "/lehre/main"
    weight: 100
  - name: "Statistik I"
    pre: "<i class='fas fa-chart-pie'></i>&ensp;"
    url: "/lehre/main#statistik-i"
    parent: 'Lehre'
    weight: 101
  - name: "Statistik II"
    pre: "<i class='fas fa-chart-bar'></i>&ensp;"
    url: "/lehre/main#statistik-ii"
    parent: "Lehre"
    weight: 102
  - name: "Multivariat"
    pre: "<i class='fas fa-bezier-curve'></i>&ensp;"
    url: "/lehre/main#multivariat"
    parent: "Lehre"
    weight: 103
  - name: "KliPPs Methoden"
    pre: "<i class='fas fa-chart-line'></i>&ensp;"
    url: "/lehre/main#klipps"
    parent: "Lehre"
    weight: 104
#  - name: "Forschungsmod. F&E"
#    pre: "<i class='fas fa-laptop-code'></i>&ensp;"
#    url: "/lehre/main#MSc5_fe"
#    parent: "Lehre"
#    weight: 105
  - name: "Weitere Lehrinhalte"
    pre: "<i class='fas fa-user-plus'></i>&ensp;"
    url: "/lehre/main#add-ons"
    parent: "Lehre"
    weight: 105

  - name: "LIFOS"
    pre: "<i class='fas fa-book-open'></i>&ensp;"
    url: '/lifos/main'
    weight: 200
  - name: "LIFOS Grundlagen"
    pre: "<i class='far fa-folder-open'></i>&ensp;"
    url: '/lifos/main#lifos-grundlagen'
    parent: "LIFOS"
    weight: 201
  - name: "LIFOS Extras"
    pre: "<i class='fab fa-gitlab'></i>&ensp;"
    url: '/lifos/main#lifos-extras'
    parent: "LIFOS"
    weight: 202

  - name: "Projekte"
    pre: "<i class='fas fa-laptop'></i>&ensp;"
    url: '/projekte/main'
    weight: 300
  - name: "Verbentrainer"
    pre: "<i class='fas fa-language'></i>&ensp;"
    url: '/projekte/main#projekt-1'
    parent: "Projekte"
    weight: 301
  - name: "Trends"
    pre: "<i class='fab fa-google'></i>&ensp;"
    url: '/projekte/main#projekt-2'
    parent: "Projekte"
    weight: 302
  - name: "Casino"
    pre: "<i class='fas fa-dice'></i>&ensp;"
    url: '/projekte/main#projekt-3'
    parent: "Projekte"
    weight: 303
  - name: "WhatsApp"
    pre: "<i class='fab fa-whatsapp'></i>&ensp;"
    url: '/projekte/main#projekt-4'
    parent: "Projekte"
    weight: 304    

  - name: "Workshops"
    pre: "<i class='fas fa-people-line'></i>&ensp;"
    url: '/workshops/main'
    weight: 400

  - name: "ggplotting"
    pre: "<i class='fas fa-palette'></i>&ensp;"
    url: '/workshops/main#ggplotting'
    parent: "Workshops"
    weight: 401

  - name: "RefresheR"
    pre: "<i class='fas fa-champagne-glasses'></i>&ensp;"
    url: '/workshops/main#refresher'
    parent: "Workshops"
    weight: 402

  - name: "KiJu"
    pre: "<i class='fas fa-baby'></i>&ensp;"
    url: '/workshops/main#kiju'
    parent: "Workshops"
    weight: 403

  - name: "Extras"
    pre: "<i class='fas fa-rocket'></i>&ensp;"
    url: '/extras/main'
    weight: 500

  - name: "DYNAMIC"
    pre: "<i class='fas fa-bolt'></i>&ensp;"
    url: '/extras/main#dynamic'
    parent: "Extras"
    weight: 501

  - name: "Git"
    pre: "<i class='fab fa-github'></i>&ensp;"
    url: '/extras/main#git'
    parent: "Extras"
    weight: 502
 
  - name: "Bayes"
    pre: "<i class='fas fa-mug-hot'></i>&ensp;"
    url: '/extras/main#bayes'
    parent: "Extras"
    weight: 503

  - name: "tigeR"
    pre: "<i class='fas fa-paw'></i>&ensp;"
    url: 'https://tiger.uni-frankfurt.de/app/shinytigeR'
    weight: 600  
  # - name: "Bayes"
  #   pre: "<i class='fa-solid fa-dice-d20'></i>&ensp;"
  #   url: '/extras/main#bayes'
  #   parent: 'Extras'
  #   weight: 401
  # 
  # - name: "stuart"
  #   pre: "<i class='fa fa-bugs'></i>&ensp;"
  #   url: '/extras/main#stuart'
  #   parent: 'Extras'
  #   weight: 402


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
